### ISSUE TITLE
Does not currently build on Rust 1.30 (currently beta)

### ISSUE THREAD

**Issue by icefoxen** [ferristseng/rust-ipfs-api#18]
rustc issue here: https://github.com/rust-lang/rust/issues/54471

Error message:

```
   Compiling ipfs-api v0.5.0-alpha1 (/home/icefox/tmp/rust-ipfs-api/ipfs-api)
error[E0432]: unresolved imports `response::BitswapStatResponse`, `response::RepoStatResponse`
 --> ipfs-api/src/response/stats.rs:9:16
  |                                                                                                   9 | use response::{BitswapStatResponse, RepoStatResponse};
  |                ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^ no `RepoStatResponse` in `response`. Did you
mean to use `ResolveResponse`?
  |                |
  |                no `BitswapStatResponse` in `response`. Did you mean to use `BitswapUnwantResponse`
?

error: cannot determine resolution for the attribute macro `serde`
  --> ipfs-api/src/response/bitswap.rs:12:3
   |
12 | #[serde(rename_all = "PascalCase")]
   |   ^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the attribute macro `serde`
  --> ipfs-api/src/response/bitswap.rs:24:3
   |
24 | #[serde(rename_all = "PascalCase")]
   |   ^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports
 ...
```

...plus a lot more serde stuff.  Full build log available here: https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/ipfs-api-0.5.0-alpha2/log.txt

**Comment by ferristseng** [comment]
Tested it recently, and this should be fixed I think with the latest nightly.
